version: '3.8'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    ports:
      - "7002:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  app:
    build: ./ 
    ports:
      - "3002:3000"
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://user:password@postgres:5432/mydb
    volumes:
      - ./backend:/usr/src/app  # Mount local backend directory
    command: ["npm", "run", "dev"]  # Adjust based on your setup

volumes:
  postgres-data:
