"use client";
import { type NextPage } from "next";
import Head from "next/head";
import { useState } from "react";
import QRCode from "qrcode";

const Home: NextPage = () => {
  const [url, setUrl] = useState<string>(""); //url
  const [src, setSrc] = useState<string>(""); //QRpic

  const generate = () => {
    QRCode.toDataURL(`${url}`).then(setSrc);
  };

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* The QRCode img */}
      <img src={src} />

      {/* username input field */}
      <input
        className="bg-black text-white"
        type="text"
        value={url}
        onChange={(e) => setUrl(e.target.value)}
      />

      {/* generate button*/}
      <button type="button" onClick={generate}>
        Generate
      </button>
    </>
  );
};

export default Home;
